/**
 * Bundled static seed catalog (Phase 1 data source).
 *
 * A curated list of well-known TUIs. In Phase 2+ this is superseded by the
 * remote registry index and kept as an offline fallback. Detection reuses the
 * exact same match logic against whichever catalog is active.
 */

import type { AppEntry, Catalog, CategoryDef } from "./types.ts";

export const SEED_CATEGORIES: CategoryDef[] = [
  { id: "dev", name: "Development", order: 10 },
  { id: "git", name: "Git & VCS", order: 20 },
  { id: "system", name: "System & Monitoring", order: 30 },
  { id: "files", name: "File Management", order: 40 },
  { id: "editors", name: "Editors", order: 50 },
  { id: "network", name: "Network", order: 60 },
  { id: "media", name: "Media", order: 70 },
  { id: "productivity", name: "Productivity", order: 80 },
  { id: "shells", name: "Shells & Multiplexers", order: 90 },
  { id: "misc", name: "Miscellaneous", order: 100 },
];

export const SEED_ENTRIES: AppEntry[] = [
  {
    id: "lazygit",
    name: "lazygit",
    description: "Simple terminal UI for git commands",
    categories: ["git", "dev"],
    tags: ["git", "vcs", "version control"],
    binaries: ["lazygit"],
    packages: { brew: "lazygit", pacman: "lazygit", dnf: "lazygit", cargo: "lazygit" },
    install: {
      brew: "brew install lazygit",
      pacman: "pacman -S lazygit",
      dnf: "dnf install lazygit",
    },
    homepage: "https://github.com/jesseduffield/lazygit",
    repo: "https://github.com/jesseduffield/lazygit",
    popularity: 55000,
    language: "Go",
  },
  {
    id: "lazydocker",
    name: "lazydocker",
    description: "Terminal UI for docker and docker-compose",
    categories: ["dev", "system"],
    tags: ["docker", "containers"],
    binaries: ["lazydocker"],
    packages: { brew: "lazydocker" },
    install: { brew: "brew install lazydocker" },
    homepage: "https://github.com/jesseduffield/lazydocker",
    repo: "https://github.com/jesseduffield/lazydocker",
    popularity: 41000,
    language: "Go",
  },
  {
    id: "gitui",
    name: "gitui",
    description: "Blazing fast terminal UI for git written in Rust",
    categories: ["git", "dev"],
    tags: ["git", "vcs", "rust"],
    binaries: ["gitui"],
    packages: { cargo: "gitui", brew: "gitui", pacman: "gitui" },
    install: { cargo: "cargo install gitui", brew: "brew install gitui" },
    homepage: "https://github.com/extrawurst/gitui",
    repo: "https://github.com/extrawurst/gitui",
    popularity: 19000,
    language: "Rust",
  },
  {
    id: "htop",
    name: "htop",
    description: "Interactive process viewer",
    categories: ["system"],
    tags: ["process", "monitor", "cpu", "memory"],
    binaries: ["htop"],
    packages: { brew: "htop", apt: "htop", pacman: "htop", dnf: "htop" },
    install: { brew: "brew install htop", apt: "apt install htop" },
    homepage: "https://htop.dev",
    popularity: 6000,
    language: "C",
  },
  {
    id: "btop",
    name: "btop",
    description: "Resource monitor with a modern, colorful interface",
    categories: ["system"],
    tags: ["process", "monitor", "cpu", "gpu", "resources"],
    binaries: ["btop"],
    packages: { brew: "btop", apt: "btop", pacman: "btop", dnf: "btop" },
    install: { brew: "brew install btop", apt: "apt install btop" },
    homepage: "https://github.com/aristocratos/btop",
    repo: "https://github.com/aristocratos/btop",
    popularity: 22000,
    language: "C++",
  },
  {
    id: "bottom",
    name: "bottom",
    description: "Cross-platform graphical process/system monitor",
    categories: ["system"],
    tags: ["process", "monitor", "rust"],
    binaries: ["btm"],
    packages: { cargo: "bottom", brew: "bottom", pacman: "bottom" },
    install: { cargo: "cargo install bottom", brew: "brew install bottom" },
    homepage: "https://github.com/ClementTsang/bottom",
    repo: "https://github.com/ClementTsang/bottom",
    popularity: 11000,
    language: "Rust",
  },
  {
    id: "ranger",
    name: "ranger",
    description: "Console file manager with VI key bindings",
    categories: ["files"],
    tags: ["file manager", "vi", "python"],
    binaries: ["ranger"],
    packages: { brew: "ranger", apt: "ranger", pacman: "ranger", pipx: "ranger" },
    install: { brew: "brew install ranger", pipx: "pipx install ranger" },
    homepage: "https://ranger.github.io",
    repo: "https://github.com/ranger/ranger",
    popularity: 15000,
    language: "Python",
  },
  {
    id: "yazi",
    name: "yazi",
    description: "Blazing fast terminal file manager written in Rust",
    categories: ["files"],
    tags: ["file manager", "rust", "async"],
    binaries: ["yazi"],
    packages: { cargo: "yazi-fs", brew: "yazi", pacman: "yazi" },
    install: { brew: "brew install yazi", pacman: "pacman -S yazi" },
    homepage: "https://yazi-rs.github.io",
    repo: "https://github.com/sxyazi/yazi",
    popularity: 24000,
    language: "Rust",
    launch: {
      args: [
        {
          name: "path",
          description: "Directory to open",
          required: false,
          placeholder: "~/projects",
          default: ".",
        },
      ],
    },
  },
  {
    id: "nnn",
    name: "nnn",
    description: "Full-featured terminal file manager, tiny and fast",
    categories: ["files"],
    tags: ["file manager", "c"],
    binaries: ["nnn"],
    packages: { brew: "nnn", apt: "nnn", pacman: "nnn", dnf: "nnn" },
    install: { brew: "brew install nnn", apt: "apt install nnn" },
    homepage: "https://github.com/jarun/nnn",
    repo: "https://github.com/jarun/nnn",
    popularity: 19000,
    language: "C",
  },
  {
    id: "neovim",
    name: "Neovim",
    description: "Hyperextensible Vim-based text editor",
    categories: ["editors", "dev"],
    tags: ["vim", "editor", "lua"],
    binaries: ["nvim"],
    packages: { brew: "neovim", apt: "neovim", pacman: "neovim", dnf: "neovim" },
    install: { brew: "brew install neovim", apt: "apt install neovim" },
    homepage: "https://neovim.io",
    repo: "https://github.com/neovim/neovim",
    popularity: 85000,
    language: "C/Lua",
    launch: {
      args: [
        {
          name: "file",
          description: "File or directory to open",
          required: false,
          placeholder: "path/to/file",
        },
      ],
    },
  },
  {
    id: "helix",
    name: "Helix",
    description: "A post-modern modal text editor",
    categories: ["editors", "dev"],
    tags: ["editor", "modal", "rust"],
    binaries: ["hx"],
    packages: { cargo: "helix-term", brew: "helix", pacman: "helix" },
    install: { brew: "brew install helix", pacman: "pacman -S helix" },
    homepage: "https://helix-editor.com",
    repo: "https://github.com/helix-editor/helix",
    popularity: 35000,
    language: "Rust",
  },
  {
    id: "vim",
    name: "Vim",
    description: "The ubiquitous text editor",
    categories: ["editors"],
    tags: ["editor", "modal"],
    binaries: ["vim"],
    packages: { brew: "vim", apt: "vim", pacman: "vim", dnf: "vim" },
    install: { brew: "brew install vim", apt: "apt install vim" },
    homepage: "https://www.vim.org",
    popularity: 37000,
    language: "C",
  },
  {
    id: "k9s",
    name: "k9s",
    description: "Kubernetes CLI to manage clusters in style",
    categories: ["dev", "system"],
    tags: ["kubernetes", "k8s", "cluster"],
    binaries: ["k9s"],
    packages: { brew: "k9s", pacman: "k9s" },
    install: { brew: "brew install k9s" },
    homepage: "https://k9scli.io",
    repo: "https://github.com/derailed/k9s",
    popularity: 28000,
    language: "Go",
  },
  {
    id: "gping",
    name: "gping",
    description: "Ping, but with a graph",
    categories: ["network"],
    tags: ["ping", "network", "graph"],
    binaries: ["gping"],
    packages: { cargo: "gping", brew: "gping", pacman: "gping" },
    install: { cargo: "cargo install gping", brew: "brew install gping" },
    homepage: "https://github.com/orf/gping",
    repo: "https://github.com/orf/gping",
    popularity: 11000,
    language: "Rust",
  },
  {
    id: "bandwhich",
    name: "bandwhich",
    description: "Terminal bandwidth utilization tool",
    categories: ["network", "system"],
    tags: ["bandwidth", "network", "rust"],
    binaries: ["bandwhich"],
    packages: { cargo: "bandwhich", brew: "bandwhich", pacman: "bandwhich" },
    install: { cargo: "cargo install bandwhich" },
    homepage: "https://github.com/imsnif/bandwhich",
    repo: "https://github.com/imsnif/bandwhich",
    popularity: 10000,
    language: "Rust",
  },
  {
    id: "spotify-tui",
    name: "spotify-tui",
    description: "Spotify client for the terminal",
    categories: ["media"],
    tags: ["spotify", "music", "player"],
    binaries: ["spt"],
    packages: { cargo: "spotify-tui", brew: "spotify-tui" },
    install: { cargo: "cargo install spotify-tui" },
    homepage: "https://github.com/Rigellute/spotify-tui",
    repo: "https://github.com/Rigellute/spotify-tui",
    popularity: 18000,
    language: "Rust",
  },
  {
    id: "cmus",
    name: "cmus",
    description: "Small, fast and powerful console music player",
    categories: ["media"],
    tags: ["music", "player", "audio"],
    binaries: ["cmus"],
    packages: { brew: "cmus", apt: "cmus", pacman: "cmus", dnf: "cmus" },
    install: { brew: "brew install cmus", apt: "apt install cmus" },
    homepage: "https://cmus.github.io",
    popularity: 6000,
    language: "C",
  },
  {
    id: "taskwarrior-tui",
    name: "taskwarrior-tui",
    description: "A terminal user interface for Taskwarrior",
    categories: ["productivity"],
    tags: ["todo", "tasks", "gtd"],
    binaries: ["taskwarrior-tui"],
    packages: { cargo: "taskwarrior-tui", brew: "taskwarrior-tui" },
    install: { cargo: "cargo install taskwarrior-tui" },
    homepage: "https://github.com/kdheepak/taskwarrior-tui",
    repo: "https://github.com/kdheepak/taskwarrior-tui",
    popularity: 3000,
    language: "Rust",
  },
  {
    id: "calcure",
    name: "calcure",
    description: "Modern TUI calendar and task manager",
    categories: ["productivity"],
    tags: ["calendar", "tasks", "calculator", "python"],
    binaries: ["calcure"],
    packages: { pipx: "calcure", pacman: "calcure" },
    install: { pipx: "pipx install calcure" },
    homepage: "https://github.com/anufrievroman/calcure",
    repo: "https://github.com/anufrievroman/calcure",
    popularity: 1600,
    language: "Python",
  },
  {
    id: "tuir",
    name: "tuir",
    description: "Browse Reddit from your terminal",
    categories: ["misc", "productivity"],
    tags: ["reddit", "news"],
    binaries: ["tuir"],
    packages: { pipx: "tuir" },
    install: { pipx: "pipx install tuir" },
    homepage: "https://gitlab.com/ajak/tuir",
    popularity: 500,
    language: "Python",
  },
  {
    id: "hunk",
    name: "hunk",
    description: "Interactive diff viewer for the terminal",
    categories: ["dev", "git"],
    tags: ["diff", "git", "review"],
    binaries: ["hunk"],
    packages: { npm: "hunk", bun: "hunk" },
    install: { npm: "npm install -g hunk", bun: "bun install -g hunk" },
    language: "JavaScript",
  },
  {
    id: "tig",
    name: "tig",
    description: "Text-mode interface for git",
    categories: ["git"],
    tags: ["git", "vcs", "browser"],
    binaries: ["tig"],
    packages: { brew: "tig", apt: "tig", pacman: "tig", dnf: "tig" },
    install: { brew: "brew install tig", apt: "apt install tig" },
    homepage: "https://jonas.github.io/tig",
    repo: "https://github.com/jonas/tig",
    popularity: 12000,
    language: "C",
  },
];

export function getSeedCatalog(): Catalog {
  return {
    entries: SEED_ENTRIES,
    categories: SEED_CATEGORIES,
    source: "seed",
  };
}
